# https://alacritty.org/config-alacritty.html
[font]
size = 16
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
# normal = { family = "JetBrains Mono", style = "Regular" }
# normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[colors]
primary = { background = "#000000" }

[window]
# opacity = 0.7
blur = true
decorations = "None"

# [[hints.enabled]]
# regex = "(ipfs:|ipns:|magnet:|mailto:|gyyemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
# hyperlinks = true
# command = "open"
# post_processing = true

[cursor]
#style = "Block"
# Set to false to disable completely
smooth_motion = true
# 0.0 = cursor is not moving, 1.0 = cursor moves instantly
smooth_motion_factor = 0.8
# 0.0 = broken, 1.0 = cursor shape is unaffected by movement
smooth_motion_spring = 0.5
# Limits how the cursor size may change
smooth_motion_max_stretch_x = 3.0
smooth_motion_max_stretch_y = 3.0
# Override "block" cursor if you don't like how it looks in this fork
# I prefer "underline"
# block_replace_shape = "underline"


# [[keyboard.bindings]]
# key = "1"
# mods = "Command"
# chars = "\u001b1"


# [[keyboard.bindings]]
# key = "2"
# mods = "Command"
# chars = "\u001b2"
#
# [[keyboard.bindings]]
# key = "3"
# mods = "Command"
# chars = "\u001b3"
#
# [[keyboard.bindings]]
# key = "4"
# mods = "Command"
# chars = "\u001b4"
#
# [[keyboard.bindings]]
# key = "A"
# mods = "Command"
# chars = "\u001ba"

# [[keyboard.bindings]]
# key = "D"
# mods = "Command"
# chars = "\u001bd"

# [[keyboard.bindings]]
# key = "E"
# mods = "Command"
# chars = "\u001be"

# [[keyboard.bindings]]
# key = "F"
# mods = "Command|Shift"
# chars = "\u001bF"

# [[keyboard.bindings]]
# key = "S"
# mods = "Command"
# chars = "\u001bs"

# [[keyboard.bindings]]
# key = "L"
# mods = "Command"
# chars = "\u001bl"
#
# [[keyboard.bindings]]
# key = "M"
# mods = "Command|Shift"
# chars = "\u001bM"

# [[keyboard.bindings]]
# key = "O"
# mods = "Command|Shift"
# chars = "\u001bO"

[[keyboard.bindings]]
key = "Semicolon"
mods = "Command|Control"
action = "ToggleViMode"

# [[keyboard.bindings]]
# key = "1"
# mods = "Command|Control"
# chars = "\u001b5"
