# JetBrains Dark palette from jb.nvim.
# Source: /Users/yelog/.local/share/nvim/lazy/jb.nvim/extras/kitty/jb-dark.conf

# Basic colors
foreground #bcbec3
background #1e1f22
selection_foreground #bcbec3
selection_background #214283
url_color #6b6c73

# Cursor
cursor #cfd0d4
cursor_text_color #1e1f22

# Window borders
active_border_color #3f4043
inactive_border_color #1e1f22
bell_border_color #ffc66d

# Tab bar
active_tab_background #43454a
active_tab_foreground #dfe1e5
inactive_tab_background #1e1f22
inactive_tab_foreground #dfe1e5
tab_bar_background #1e1f22
tab_bar_margin_color #1e1f22

# ANSI colors
color0 #1e1f22
color1 #f75464
color2 #6aab73
color3 #fbc36c
color4 #57a8f5
color5 #c87dbb
color6 #4083c8
color7 #bcbec3
color8 #7a7e85
color9 #f75464
color10 #6aab73
color11 #fbc36c
color12 #57a8f5
color13 #c87dbb
color14 #4083c8
color15 #bcbec3
