[manager]
prepend_keymap = [
	{ on = "i", run = 'plugin smart-enter' },
  { on = "S", run = 'shell "$SHELL" --block --confirm' },
]

# keymap = [
#   { on = "S", run = 'shell "$SHELL" --block --confirm' },
# ]
