return {
  -- "olimorris/codecompanion.nvim",
  -- dependencies = {
  --   "nvim-lua/plenary.nvim",
  --   "nvim-treesitter/nvim-treesitter",
  -- },
  -- config = function()
  --   require("codecompanion").setup({
  --     strategies = {
  --       chat = {
  --         adapter = "copilot",
  --       },
  --       inline = {
  --         adapter = "copilot",
  --       },
  --     },
  --     adapters = {
  --       proxyOpenAi = function()
  --         return require("codecompanion.adapters").extend("openai_compatible", {
  --           env = {
  --             url = "https://api.chatanywhere.tech",                           -- optional: default value is ollama url http://127.0.0.1:11434
  --             api_key = "sk-n3BRr5bMxf77DSDFvGqac4q0ICPcUbNChiDFvDnCWX2YYp31", -- optional: if your endpoint is authenticated
  --             chat_url = "/v1/chat/completions",                               -- optional: default value, override if different
  --           },
  --         })
  --       end,
  --     },
  --   })
  -- end
}
