return {
  -- "ellisonleao/gruvbox.nvim",
  -- config = function()
  --   vim.o.background = "dark" -- or "light" for light mode
  --   require("gruvbox").setup({
  --     undercurl = true,
  --     underline = true,
  --     bold = true,
  --     italic = true,
  --     strikethrough = true,
  --     invert_selection = false,
  --     invert_signs = false,
  --     invert_tabline = false,
  --     invert_intend_guides = false,
  --     inverse = true, -- invert background for search, diffs, statuslines and errors
  --     contrast = "", -- can be "hard", "soft" or empty string
  --     overrides = {
  --       markdownH1 = { fg = "#F99417" },
  --       markdownH2 = { fg = "#FFED00" },
  --       markdownH3 = { fg = "#16FF00" },
  --       markdownH4 = { fg = "#30E3DF" },
  --     },
  --     dim_inactive = false,
  --     transparent_mode = false,
  --     palette_overrides = {
  --       -- bright_green = "#C58940"
  --     },
  --   })
  --   vim.cmd([[colorscheme gruvbox]])
  -- end
}

