require('config.comment')
require('config.toggleterm')
require('config.bufferline')
require('config.telescope')
require('config.lualine')
require('config.auto-session')
require('config.wilder')
require('config.null-ls')
