require('utils')
require('utils.plugins')

require('core.key-map')

require('config.colorscheme')
require('config.comment')
-- require('config.toggleterm')
require('config.bufferline')
require('config.telescope')
require('config.lualine')
require('config.auto-session')
require('config.wilder')
require('config.null-ls')
require('config.neo-tree')
require('config.which-key')
require('config.markdown')
require('config.bullets')
require('config.lsp')
require('config.cmp')
require('config.neodev')
