version = 6

[[groups]]
id = "ca9a4c5a-9779-456a-8cec-ff11e53bdf6d"
name = "生产环境"

[[profiles]]
id = "7e1cc7b3-62e3-4a66-8688-20b8ba9d5bd4"
name = "lssc-uat"
group_id = "ca9a4c5a-9779-456a-8cec-ff11e53bdf6d"
kind = "postgres"
url_format = "jdbc-postgre-sql"
host = "10.188.132.29"
port = 9338
user = "a_appconnect"
database = "moss_biz"
default_schema = "tools"
ssl_mode = "prefer"
read_only = false
environment = "development"

[profiles.access]
scope = "projects"
roots = ["/Users/yelog/workspace/tui/lazydb"]

[profiles.credential_policy]
policy = "local_encrypted"

[profiles.credential_policy.reference]
version = 1
nonce = "+P46IUPL9GDwX455ko9Cg75pnBrEuK70"
ciphertext = "0mI6PdTXpSQjaiI16dyYPBLnsiR8k/ZAe0c1YyxujlU1"

[profiles.catalog_scope.databases]
mode = "selected"

[[profiles.catalog_scope.databases.items]]
name = "moss_biz"

[profiles.catalog_scope.databases.items.schemas]
mode = "selected"
items = [
    "test_schema",
    "tools",
]

[[profiles]]
id = "9d5aa2da-9f31-4dbc-b2b6-0844ff79b41e"
name = "moss-sit"
kind = "postgres"
url_format = "jdbc-postgre-sql"
host = "10.196.178.221"
port = 30345
user = "moss"
database = "moss"
default_schema = "tools"
ssl_mode = "prefer"
read_only = false
environment = "development"

[profiles.access]
scope = "global"

[profiles.credential_policy]
policy = "local_encrypted"

[profiles.credential_policy.reference]
version = 1
nonce = "7thwyoz1EoXw/0miRklmRxVT6hOf5CSG"
ciphertext = "1zdwb7X67PwBPu/4LUnzMqGz0Oaotvq+qWQCCTKbGT9Q4k6E"

[profiles.catalog_scope.databases]
mode = "selected"

[[profiles.catalog_scope.databases.items]]
name = "moss"

[profiles.catalog_scope.databases.items.schemas]
mode = "selected"
items = ["tools"]

[[profiles]]
id = "9618b337-e880-4ae5-bcee-029e36de266b"
name = "kms-uat"
kind = "postgres"
url_format = "jdbc-postgre-sql"
host = "10.188.132.30"
port = 5555
user = "lemes"
database = "kms"
default_schema = "tools"
ssl_mode = "prefer"
read_only = false
environment = "development"

[profiles.access]
scope = "global"

[profiles.credential_policy]
policy = "local_encrypted"

[profiles.credential_policy.reference]
version = 1
nonce = "tsbi7SvzbtV4GUWO0sr9BxV7aXBU+XaH"
ciphertext = "ksq66PJuAcX8Tr/aksFHaAF3uxZvJZMW8UrJ+g=="

[profiles.catalog_scope.databases]
mode = "selected"

[[profiles.catalog_scope.databases.items]]
name = "kms"

[profiles.catalog_scope.databases.items.schemas]
mode = "selected"
items = [
    "lkms",
    "report",
    "tools",
]

[[profiles]]
id = "91c4e050-d62d-4a28-a985-5baf8a72ea18"
name = "yili-184"
kind = "mysql"
url_format = "jdbc-my-sql"
host = "10.196.173.184"
port = 30031
user = "root"
database = "hrjqp"
ssl_mode = "prefer"
read_only = false
environment = "development"

[profiles.access]
scope = "global"

[profiles.credential_policy]
policy = "local_encrypted"

[profiles.credential_policy.reference]
version = 1
nonce = "Ki4YUgvIKZDrjlByWSAv3tKzIz4Fiw/3"
ciphertext = "g2Z4rmf2KUhYeiPSJR0I6+1JRqEtM+DbJijDgiqQ57pyfwiU"

[profiles.catalog_scope.databases]
mode = "selected"

[[profiles.catalog_scope.databases.items]]
name = "hrjqp"

[profiles.catalog_scope.databases.items.schemas]
mode = "all"
