-- 判断是否为 Alacritty 应用
-- local function isAlacrittyApp()
--   local app = hs.application.frontmostApplication()
--   if app ~= nil and app:bundleID() == "org.alacritty" then
--     return true
--   end
--   return false
-- end
--
-- -- 监听全局按键事件
-- hs.hotkey.bind({ "ctrl" }, "w", function()
--   -- 如果是 Alacritty 应用，直接返回
--   if isAlacrittyApp() then
--     return
--   else
--     -- 发送模拟按键事件，删除前一个单词
--     hs.eventtap.keyStroke({ "alt" }, "delete")
--   end
-- end)

